### ISSUE TITLE
Theres no texture for the item 'Purified Water Bottle'

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#34] opened 2021-12-27 21:59 UTC
(obtained from right clicking a glass bottle on the purified water)

**Comment by SalvieMundi** [comment] 2021-12-27 22:05
Can't reproduce. If you've added any additional resource packs or modified the order in which they load, let me know, as that can cause this issue, as well as additional issues with enchantments and potions.

**Comment by Tigerboy007** [comment] 2021-12-27 22:29
strange

**Comment by SalvieMundi** [comment] 2021-12-28 13:18
After updating to the newest client (do a full new install, don't use the update client option), try to log on to the server and see if this is still happening. I'm betting a fresh install fixes the issue.

**Comment by Tigerboy007** [comment] 2022-01-13 02:32
yeah this is fixed sorry I forgot to check!

**Comment by SalvieMundi** [comment] 2022-01-13 05:55
closing on request of op

**Closed as completed by SalvieMundi** 2022-01-13 05:55 UTC
Labels: bug, question, aesthetics
