### ISSUE TITLE
grindstones cant remove 'core of ___' enchantment from armour

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#28] opened 2021-12-21 03:04 UTC
works with 'core of Neptune', 'core of purity', 'core of the blood god', and 'core of the warp', HOWEVER if you add both armour to the grindstone, the enchantments get merged, which isn't something that can be done in an anvil

**Comment by Tigerboy007** [comment] 2021-12-21 03:05
oh and other enchantments can still be removed, including ones from the same mod

**Comment by Tigerboy007** [comment] 2021-12-21 03:07
wearing the armour with all 4 'core' enchantments causes the health bar to glitch slightly, as one of them adds more max health and one of them lowers the max health

**Comment by SalvieMundi** [comment] 2021-12-21 03:54
Will check into this series of issues with Herb's Enchantments tomorrow. There's definitely some buggy stuff here. Enchantments are inherently difficult to program bugs out of, I find.

With that said, I think the grindstone behavior is because these "core of" enchantments are actually similar to curse of binding, in that you actually can't remove them. Could be wrong tho, this was a mod I worked on over 2 months ago. 🤣

**Comment by SalvieMundi** [comment] 2021-12-21 13:30
Confirmed that the "Core Of" enchantments are indeed treasure enchantments that can't be found in an enchanting table and shouldn't be able to be removed via grindstone.

See the Herb's Extra Enchants descriptor (bottom of page): https://github.com/herb-mc/extra_enchants
See the disenchanting info from MC Wiki: https://minecraft.fandom.com/wiki/Enchanting#Disenchanting

Will check the third issue later.

**Comment by SalvieMundi** [comment] 2021-12-26 11:48
Enchanting each of my four pieces of armor with a different "core" enchantment does not produce this issue. Tried adding all four to just a single piece of armor is impossible in survival as the enchantments are all exclusive of each other. Resolving issue.

**Closed as completed by SalvieMundi** 2021-12-26 11:48 UTC
Labels: bug, aesthetics, gameplay, requires research, minor, mods
